//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apogee.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apogee.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your account has been blocked after 3 bad passwords, time remaining : #1 minutes.
        /// </summary>
        public static string AccountBlocked {
            get {
                return ResourceManager.GetString("AccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In alphabetical order.
        /// </summary>
        public static string Alpha {
            get {
                return ResourceManager.GetString("Alpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborator is already archived.
        /// </summary>
        public static string AlreadyArchived {
            get {
                return ResourceManager.GetString("AlreadyArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have already deleted the photo.
        /// </summary>
        public static string AlreadyDelete {
            get {
                return ResourceManager.GetString("AlreadyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have already uploaded a photo.
        /// </summary>
        public static string AlreadyUpload {
            get {
                return ResourceManager.GetString("AlreadyUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your annual salary.
        /// </summary>
        public static string AnnualSalary {
            get {
                return ResourceManager.GetString("AnnualSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Archive.
        /// </summary>
        public static string Archive {
            get {
                return ResourceManager.GetString("Archive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bank.
        /// </summary>
        public static string Area1 {
            get {
                return ResourceManager.GetString("Area1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Distribution.
        /// </summary>
        public static string Area10 {
            get {
                return ResourceManager.GetString("Area10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Services.
        /// </summary>
        public static string Area11 {
            get {
                return ResourceManager.GetString("Area11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transport.
        /// </summary>
        public static string Area12 {
            get {
                return ResourceManager.GetString("Area12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Public sector.
        /// </summary>
        public static string Area13 {
            get {
                return ResourceManager.GetString("Area13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Luxury.
        /// </summary>
        public static string Area14 {
            get {
                return ResourceManager.GetString("Area14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other.
        /// </summary>
        public static string Area15 {
            get {
                return ResourceManager.GetString("Area15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Assurance.
        /// </summary>
        public static string Area2 {
            get {
                return ResourceManager.GetString("Area2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Health.
        /// </summary>
        public static string Area3 {
            get {
                return ResourceManager.GetString("Area3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pharmaceutical.
        /// </summary>
        public static string Area4 {
            get {
                return ResourceManager.GetString("Area4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Social protection.
        /// </summary>
        public static string Area5 {
            get {
                return ResourceManager.GetString("Area5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Industry.
        /// </summary>
        public static string Area6 {
            get {
                return ResourceManager.GetString("Area6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Food industry.
        /// </summary>
        public static string Area7 {
            get {
                return ResourceManager.GetString("Area7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Automotive.
        /// </summary>
        public static string Area8 {
            get {
                return ResourceManager.GetString("Area8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aeronautics / Space / Defense.
        /// </summary>
        public static string Area9 {
            get {
                return ResourceManager.GetString("Area9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Businessman invalid.
        /// </summary>
        public static string BusinessInvalid {
            get {
                return ResourceManager.GetString("BusinessInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certification.
        /// </summary>
        public static string Certification {
            get {
                return ResourceManager.GetString("Certification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Certifications.
        /// </summary>
        public static string Certifications {
            get {
                return ResourceManager.GetString("Certifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 100% available.
        /// </summary>
        public static string Charge100 {
            get {
                return ResourceManager.GetString("Charge100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Coefficients invalid.
        /// </summary>
        public static string CoefficientsInvalid {
            get {
                return ResourceManager.GetString("CoefficientsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formation Collaborateur.
        /// </summary>
        public static string CollabForm {
            get {
                return ResourceManager.GetString("CollabForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Information.
        /// </summary>
        public static string CollabInfo {
            get {
                return ResourceManager.GetString("CollabInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Management Collaborator .
        /// </summary>
        public static string CollabManag {
            get {
                return ResourceManager.GetString("CollabManag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formation monitoring.
        /// </summary>
        public static string CollabMonit {
            get {
                return ResourceManager.GetString("CollabMonit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborater.
        /// </summary>
        public static string Collaborater {
            get {
                return ResourceManager.GetString("Collaborater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à List of collaborateurs.
        /// </summary>
        public static string CollaboraterEdit {
            get {
                return ResourceManager.GetString("CollaboraterEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collaborator.
        /// </summary>
        public static string Collaborator {
            get {
                return ResourceManager.GetString("Collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The contact person is already deleted!.
        /// </summary>
        public static string ContactAlreadyDelete {
            get {
                return ResourceManager.GetString("ContactAlreadyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The contact person has been deleted.
        /// </summary>
        public static string ContactDelete {
            get {
                return ResourceManager.GetString("ContactDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Person to contact in case of emergency.
        /// </summary>
        public static string ContactEmergency {
            get {
                return ResourceManager.GetString("ContactEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the contact person?.
        /// </summary>
        public static string ContactEmergencyConfirm {
            get {
                return ResourceManager.GetString("ContactEmergencyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creation of a contact person.
        /// </summary>
        public static string ContactEmergencyCreat {
            get {
                return ResourceManager.GetString("ContactEmergencyCreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modification of a contact person.
        /// </summary>
        public static string ContactEmergencyModif {
            get {
                return ResourceManager.GetString("ContactEmergencyModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Removal of a contact person.
        /// </summary>
        public static string ContactEmergencyRemove {
            get {
                return ResourceManager.GetString("ContactEmergencyRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contract invalid.
        /// </summary>
        public static string ContractInvalid {
            get {
                return ResourceManager.GetString("ContractInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copied.
        /// </summary>
        public static string Copied {
            get {
                return ResourceManager.GetString("Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Copy.
        /// </summary>
        public static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contract end date is well recorded.
        /// </summary>
        public static string DateContractRecorded {
            get {
                return ResourceManager.GetString("DateContractRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mandatory date !!.
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The start date cannot be greater than the end date !!.
        /// </summary>
        public static string DateErrorC {
            get {
                return ResourceManager.GetString("DateErrorC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting the profile picture.
        /// </summary>
        public static string DeletingPicture {
            get {
                return ResourceManager.GetString("DeletingPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Disconnect.
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Available.
        /// </summary>
        public static string Dispo {
            get {
                return ResourceManager.GetString("Dispo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End of mission in 3 months or less.
        /// </summary>
        public static string Dispo3mois {
            get {
                return ResourceManager.GetString("Dispo3mois", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your email address :.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email is not valid.
        /// </summary>
        public static string EmailInvalide {
            get {
                return ResourceManager.GetString("EmailInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An email has been sent to.
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email work is not valid.
        /// </summary>
        public static string EmailWorkInvalide {
            get {
                return ResourceManager.GetString("EmailWorkInvalide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while processing your request..
        /// </summary>
        public static string Error1 {
            get {
                return ResourceManager.GetString("Error1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect contract end date.
        /// </summary>
        public static string ErrorContratDate {
            get {
                return ResourceManager.GetString("ErrorContratDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem with photo deletion.
        /// </summary>
        public static string ErrorDelete {
            get {
                return ResourceManager.GetString("ErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à #1 attempt(s) left.
        /// </summary>
        public static string ErrorsLeft {
            get {
                return ResourceManager.GetString("ErrorsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem with employee table during contract end date update.
        /// </summary>
        public static string ErrorTableContract {
            get {
                return ResourceManager.GetString("ErrorTableContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Experiences.
        /// </summary>
        public static string Experiences {
            get {
                return ResourceManager.GetString("Experiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select the information you want to export as well as the file format :.
        /// </summary>
        public static string ExportModal {
            get {
                return ResourceManager.GetString("ExportModal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid previous password.
        /// </summary>
        public static string FalseOldPassword {
            get {
                return ResourceManager.GetString("FalseOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The files have been saved.
        /// </summary>
        public static string FileSaved {
            get {
                return ResourceManager.GetString("FileSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The files have been deleted.
        /// </summary>
        public static string FilesDelete {
            get {
                return ResourceManager.GetString("FilesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The files have been modified.
        /// </summary>
        public static string FilesModified {
            get {
                return ResourceManager.GetString("FilesModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Files must be uploaded.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Filters.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonction Competences.
        /// </summary>
        public static string FonctionCompetences {
            get {
                return ResourceManager.GetString("FonctionCompetences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forgot password.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You have sent a password reset request.
        ///Below is a temporary password that is only valid for one hour from the reset request.
        ///You will then have to modify it after your connection..
        /// </summary>
        public static string ForgotPasswordParagraph {
            get {
                return ResourceManager.GetString("ForgotPasswordParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formation.
        /// </summary>
        public static string Formation {
            get {
                return ResourceManager.GetString("Formation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formations.
        /// </summary>
        public static string Formations {
            get {
                return ResourceManager.GetString("Formations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grade invalid.
        /// </summary>
        public static string GradeInvalid {
            get {
                return ResourceManager.GetString("GradeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à To import an employee, you must have the latest version of the skills file.
        ///Some information may not be retrieved if it is not in the correct styles in the file, please check after importing.
        ///Functional skills are not imported, manual entry is required..
        /// </summary>
        public static string ImportParagraph {
            get {
                return ResourceManager.GetString("ImportParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failed : Incorrect password !.
        /// </summary>
        public static string IncorrectPsw {
            get {
                return ResourceManager.GetString("IncorrectPsw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unavailable on long-term mission.
        /// </summary>
        public static string Indispo {
            get {
                return ResourceManager.GetString("Indispo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connection failed : User does not exist !.
        /// </summary>
        public static string InexistUser {
            get {
                return ResourceManager.GetString("InexistUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Employee&apos;s personal information.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Informations.
        /// </summary>
        public static string Informations {
            get {
                return ResourceManager.GetString("Informations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Initials.
        /// </summary>
        public static string Initials {
            get {
                return ResourceManager.GetString("Initials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Follow the instructions provided to reset your password..
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid availability !!.
        /// </summary>
        public static string InvalidAvail {
            get {
                return ResourceManager.GetString("InvalidAvail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid credentials.
        /// </summary>
        public static string InvalidCerdentials {
            get {
                return ResourceManager.GetString("InvalidCerdentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LanguageLevel1.
        /// </summary>
        public static string LanguageLevel1 {
            get {
                return ResourceManager.GetString("LanguageLevel1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LanguageLevel2.
        /// </summary>
        public static string LanguageLevel2 {
            get {
                return ResourceManager.GetString("LanguageLevel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LanguageLevel3.
        /// </summary>
        public static string LanguageLevel3 {
            get {
                return ResourceManager.GetString("LanguageLevel3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LanguageLevel4.
        /// </summary>
        public static string LanguageLevel4 {
            get {
                return ResourceManager.GetString("LanguageLevel4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LanguageLevel5.
        /// </summary>
        public static string LanguageLevel5 {
            get {
                return ResourceManager.GetString("LanguageLevel5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Languages.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lasts added.
        /// </summary>
        public static string LastAdded {
            get {
                return ResourceManager.GetString("LastAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à *.
        /// </summary>
        public static string Level1 {
            get {
                return ResourceManager.GetString("Level1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à **.
        /// </summary>
        public static string Level2 {
            get {
                return ResourceManager.GetString("Level2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ***.
        /// </summary>
        public static string Level3 {
            get {
                return ResourceManager.GetString("Level3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ****.
        /// </summary>
        public static string Level4 {
            get {
                return ResourceManager.GetString("Level4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à *****.
        /// </summary>
        public static string Level5 {
            get {
                return ResourceManager.GetString("Level5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mandatory input.
        /// </summary>
        public static string MandatoryInput {
            get {
                return ResourceManager.GetString("MandatoryInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matricule number exist.
        /// </summary>
        public static string MatriculeInvalid {
            get {
                return ResourceManager.GetString("MatriculeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Monthly pay is invalid.
        /// </summary>
        public static string MonthlyPayInvalid {
            get {
                return ResourceManager.GetString("MonthlyPayInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name Firstname.
        /// </summary>
        public static string NameFirstname {
            get {
                return ResourceManager.GetString("NameFirstname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your temporary password as expired, you need to reset it.
        /// </summary>
        public static string NeedToResetPassword {
            get {
                return ResourceManager.GetString("NeedToResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New Collaborator.
        /// </summary>
        public static string NewCollab {
            get {
                return ResourceManager.GetString("NewCollab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Temporary password :.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No results.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notify the administrator !!.
        /// </summary>
        public static string NotifyAdmin {
            get {
                return ResourceManager.GetString("NotifyAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à your entry is not sufficient.
        /// </summary>
        public static string NotSufficient {
            get {
                return ResourceManager.GetString("NotSufficient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order.
        /// </summary>
        public static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Other agencies.
        /// </summary>
        public static string OtherAgency {
            get {
                return ResourceManager.GetString("OtherAgency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Part-time.
        /// </summary>
        public static string PartTime {
            get {
                return ResourceManager.GetString("PartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pdf.
        /// </summary>
        public static string Pdf {
            get {
                return ResourceManager.GetString("Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profile picture creation.
        /// </summary>
        public static string PictureCreation {
            get {
                return ResourceManager.GetString("PictureCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your HireDate.
        /// </summary>
        public static string PlsDate_embauche {
            get {
                return ResourceManager.GetString("PlsDate_embauche", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your date of birth.
        /// </summary>
        public static string PlsDate_naissance {
            get {
                return ResourceManager.GetString("PlsDate_naissance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your email address.
        /// </summary>
        public static string PlsEmail {
            get {
                return ResourceManager.GetString("PlsEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your password.
        /// </summary>
        public static string PlsPassword {
            get {
                return ResourceManager.GetString("PlsPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Post.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The experiment is already deleted!.
        /// </summary>
        public static string PosteAlreadyDelete {
            get {
                return ResourceManager.GetString("PosteAlreadyDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Creating an experience.
        /// </summary>
        public static string PosteCreat {
            get {
                return ResourceManager.GetString("PosteCreat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The experiment has been deleted.
        /// </summary>
        public static string PosteDelete {
            get {
                return ResourceManager.GetString("PosteDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Editing an experience.
        /// </summary>
        public static string PosteModif {
            get {
                return ResourceManager.GetString("PosteModif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deleting an experience.
        /// </summary>
        public static string PosteRemove {
            get {
                return ResourceManager.GetString("PosteRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Are you sure you want to delete the experiment?.
        /// </summary>
        public static string PosteRemoveConfirm {
            get {
                return ResourceManager.GetString("PosteRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem with the Emergency file !!!.
        /// </summary>
        public static string ProblemEmergency {
            get {
                return ResourceManager.GetString("ProblemEmergency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem with photo import.
        /// </summary>
        public static string ProblemImport {
            get {
                return ResourceManager.GetString("ProblemImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem with the Poste file !!!.
        /// </summary>
        public static string ProblemPoste {
            get {
                return ResourceManager.GetString("ProblemPoste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Professional experiences.
        /// </summary>
        public static string ProExperiences {
            get {
                return ResourceManager.GetString("ProExperiences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet(s).
        /// </summary>
        public static string Projet {
            get {
                return ResourceManager.GetString("Projet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Reason for program termination: Problem when.
        /// </summary>
        public static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à creating a new employee.
        /// </summary>
        public static string Reason1 {
            get {
                return ResourceManager.GetString("Reason1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à reading a collaborator.
        /// </summary>
        public static string Reason2 {
            get {
                return ResourceManager.GetString("Reason2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Registration number is not valid.
        /// </summary>
        public static string RegistrationNumberInvalid {
            get {
                return ResourceManager.GetString("RegistrationNumberInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search collaborator.
        /// </summary>
        public static string SearchCollab {
            get {
                return ResourceManager.GetString("SearchCollab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Search skills.
        /// </summary>
        public static string SearchCompet {
            get {
                return ResourceManager.GetString("SearchCompet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See profile.
        /// </summary>
        public static string SeeProfiles {
            get {
                return ResourceManager.GetString("SeeProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select all.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Program stopped due to a serious error!.
        /// </summary>
        public static string SeriousError {
            get {
                return ResourceManager.GetString("SeriousError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Skills.
        /// </summary>
        public static string Skills {
            get {
                return ResourceManager.GetString("Skills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut2.
        /// </summary>
        public static string Statut2 {
            get {
                return ResourceManager.GetString("Statut2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut3.
        /// </summary>
        public static string Statut3 {
            get {
                return ResourceManager.GetString("Statut3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statut invalid.
        /// </summary>
        public static string StatutInvalid {
            get {
                return ResourceManager.GetString("StatutInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technic Competences.
        /// </summary>
        public static string TechnicalCompetences {
            get {
                return ResourceManager.GetString("TechnicalCompetences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone.
        /// </summary>
        public static string Tel_fixe {
            get {
                return ResourceManager.GetString("Tel_fixe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone mobil.
        /// </summary>
        public static string Tel_port {
            get {
                return ResourceManager.GetString("Tel_port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone work.
        /// </summary>
        public static string Tel_travail {
            get {
                return ResourceManager.GetString("Tel_travail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Level.
        /// </summary>
        public static string TitleLevel {
            get {
                return ResourceManager.GetString("TitleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technology, environment, tools.
        /// </summary>
        public static string TitleTechnic {
            get {
                return ResourceManager.GetString("TitleTechnic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Person to contact in case of emergency n ° .
        /// </summary>
        public static string TitrePerson {
            get {
                return ResourceManager.GetString("TitrePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to the application.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Welcome to Apogee.
        /// </summary>
        public static string WelcomeEmail {
            get {
                return ResourceManager.GetString("WelcomeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your account on the Apogee by Apside application has been created.
        ///You will find your login details below.
        /// </summary>
        public static string WelcomeParagraph {
            get {
                return ResourceManager.GetString("WelcomeParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Word.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
    }
}
